openapi: 3.0.2
info:
  title: Ticket Generator API
  description: Service which generates unique tickets
  version: 1.0.0
paths:
  /getTicket:
    get:
      summary: Get one ticket
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ticket'
  /getTickets:
    get:
      summary: Get many tickets
      parameters:
        - name: count
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 1000
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ticket'
components:
  schemas:
    Ticket:
      type: string
      minLength: 13
      maxLength: 13